config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  use_doorkeeper
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "questions#index"

  get :search, to: "search#index"

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit], shallow: true do
        resources :answers, except: %i[new edit]
      end
    end
  end

  resources :questions, shallow: true do
    post :subscribe, on: :member
    post :accept_vote, to: "votes#accept", on: :member, defaults: { votable: 'questions' }

    resources :comments, only: %i[create update destroy], defaults: { commentable: 'questions' }

    resources :answers, shallow: true, except: :index do
      post :accept_vote, to: "votes#accept", on: :member, defaults: { votable: 'answers' }
      resources :comments, only: %i[create update destroy], defaults: { commentable: 'answers' }
    
      post :mark_best, on: :member
    end
  end

  scope :active_storage, module: :active_storage, as: :active_storage do
      resources :attachments, only: :destroy
  end

  resources :awardings, only: :index

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Authorable
  include Commentable
  include Votable

  has_many :answers, dependent: :destroy
  has_many :links, as: :linkable, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :followers, through: :subscriptions, source: :user
  has_one :awarding
  has_many_attached :files

  validates :title, :body,  presence: true
  validates :title, uniqueness: true

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :awarding, reject_if: :all_blank, allow_destroy: true
  
  ThinkingSphinx::Callbacks.append(self, :behaviours => [:real_time])  

  after_create_commit :publish_question
  after_create_commit { |question| subscribe!(question.author) }

  def publish_question
    ActionCable.server.broadcast(
      "questions",
      to_json(include: :author, 
              methods: :rating)
    ) 
  end

  def subscribe!(user)
    subscription = subscriptions.find_or_initialize_by(user_id: user.id)
    return subscription.destroy if subscription.persisted?
    subscription.save
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource only: %i[index show create]
  before_action :load_question, only: %i[show update destroy]

  respond_to :json

  def index
    respond_with Question.all, each_serializer: Api::V1::QuestionsSerializer
  end

  def show
    respond_with @question, serializer: Api::V1::QuestionSerializer
  end

  def create
    respond_with @question = Question.create(question_params.merge(author_id: current_resource_owner.id)), serializer: Api::V1::QuestionSerializer
  end

  def update
    authorize! :update, @question

    respond_to do |format|
      if @question.update(question_params)
        format.json { render json: @question, serializer: Api::V1::QuestionSerializer }
      else
        format.json { render json: { "errors": @question.errors }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :destroy, @question
    
    respond_with(@question.destroy)
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, 
                                      links_attributes: [:id, :title, :url, :_destroy], # _destroy?
                                      awarding_attributes: [:title, :image, :_destroy]) # _destroy?
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :load_questions, only: :index
  before_action :load_question,  except: %i[index new create]
  before_action :load_answers,  only: :show
  before_action :load_comments, only: :show
  authorize_resource

  respond_to :html

  def index
  end

  def show
    gon.question_id = @question.id
  end

  def new
  end

  def create
    respond_with(@question = Question.create(question_params.merge(author_id: current_user.id)))
  end

  def edit
  end

  def update
    @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    respond_with(@question.destroy)
  end

  def subscribe
    respond_to do |format|
      format.js { @question.subscribe!(current_user) }
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, 
                                      files: [], links_attributes: [:id, :title, :url, :_destroy],
                                      awarding_attributes: [:title, :image, :_destroy])
  end

  def load_questions
    @questions = Question.with_attached_files.includes(:author)
  end

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def load_answers
    @answers = @question.answers.with_attached_files.includes(:author)
  end

  def load_comments
    @comments = @question.comments.includes(:author)
  end
end

app/views/questions/_awarding_fields.html.slim
.nested-fields
  .field
    = f.label :title
    br
    = f.text_field :title
  .field
    = f.label :image
    br
    = f.file_field :image, direct_upload: true
  = link_to_remove_association "remove awarding", f

app/views/questions/_form.html.slim
= form_with url: (question.new_record? ? questions_path : question_path(question)), model: question, local: true, id: "direct_upload_form" do |f|
  = f.label      :title
  br
  = f.text_area :title
  br
  = f.label      :body
  br
  = f.text_area  :body
  br
  - if question.files.attached?
    table.attachments
      thead 
        tr 
          th = "Attachments:"
      - question.files.each do |file|
        tr*{'attachment-id' => file.id}
          td = link_to file.filename.to_s, url_for(file)
          td
            = link_to "Delete", active_storage_attachment_path(file.id), method: :delete, remote: true, data: {confirm: "Are you sure?"}, class: "delete"
  = f.file_field :files, multiple: true, direct_upload: true
  h3 Links
  #links
    = f.fields_for :links do |link|
      = render 'shared/link_fields', f: link
    .links
      = link_to_add_association 'add link', f, :links,
        partial: 'shared/link_fields'
  h3 Awarding
  #awarding
    = f.fields_for :awarding do |awarding|
      = render 'awarding_fields', f: awarding
    .awarding.max-one-association
      = link_to_add_association 'add awarding', f, :awarding, force_non_association_create: true
  br
  = f.submit

app/views/questions/_question.html.slim
tr.question *{'item-id' => question.id}
  td = link_to "#{question.title}", question_path(question)
  td = question.author.email

app/views/questions/edit.html.slim
h2 Edit question
- if @question.errors.present?
  = render "shared/errors", resource: @question

= render "form", question: @question

= link_to "Back to questions", questions_path

app/views/questions/index.html.slim
h2 All questions
- if can? :create, Question
  = button_to "Ask question", new_question_path, method: :get
- else 
  = link_to "Sign in", new_user_session_path, method: :get    
  |  to ask questions

br
table.table#questions
  thead
    tr
      th  Title
      th  Author
  tbody
    - if @questions.present?
      = render partial: @questions
    - else
      tr
        td No questions yet.

app/views/questions/new.html.slim
- @question ||= Question.new

h2 Create new question
- if @question&.errors.present?
  = render "shared/errors", resource: @question

= render "form", question: @question

= link_to "Back to questions", questions_path

app/views/questions/show.html.slim
h1 Show question

table.question *{'item-id': @question.id}
  tr
    td
      - cache [@question, "votes"] do 
        = render partial: "shared/votes", locals: {resource: @question}
          
    td
      table
        tr
          td
            - cache [@question, "title"] do 
              h2 = "Title: #{@question.title}"
            
            - if can? :subscribe, Question
              - subscribe_button = @question.followers.include?(current_user) ? 'Unsubscribe' : 'Subscribe'
              = button_to "#{subscribe_button}", subscribe_question_path(@question), remote: true, data: { type: :js }, class: "subscribe"


            - cache [@question, "body"] do   
              strong Body: 
              = @question.body
              br
              strong Author: 
              = @question.author.email
              br
            
            - cache [@question, "awarding"] do  
              - if @question.awarding.present?   
                #awarding
                  strong Awarding: 
                  = @question.awarding.title
                  br
                  = image_tag(@question.awarding.image.variant(resize_to_limit: [100, 100]))

            - if can? :update, @question
              = button_to "Edit Question", edit_question_path(@question), method: :get, local: true
            - if can? :destroy, @question
              = button_to "Delete Question", question_path(@question), method: :delete, local: true, data: { confirm: "Are you sure?" }

            - if @question.files.attached?
              table.attachments
                thead 
                  tr 
                    th = "Attachments:"
                - @question.files.each do |file|
                  tr 
                    td = link_to file.filename.to_s, url_for(file)

            - cache [@question, "links"] do
              - if @question.links.present?
                table.links
                  thead 
                    tr 
                      th = "Links:"
                  - @question.links.each do |link|
                    tr 
                      td = link_to link.title, link.url, target: "_blank"
            br
        tr
          td
            table
              tr
                td 
                  table.table.bordered.comments
                    = render @comments
              tr
                - if current_user.present?
                  - cache [@question, "new_comment_form"] do
                    = render partial: "comments/form", locals: {commentable: @question}

h3 Answers

table.answers
  tbody
    - if @answers.present?
      = render partial: @answers

div.errors

- if can? :create, Answer
  - cache [@question, "new_answer_form"] do
    = render partial: "answers/form", locals: {question: @question}  
- else 
  p 
    = link_to "Sign in", new_user_session_path, method: :get   
    |  to post answer

= link_to "Back to questions", questions_path

app/views/questions/subscribe.js.erb
var button = $(".subscribe")

if (button.attr("value") == "Subscribe") {
  button.attr("value", "Unsubscribe")
  window.alert("You have been successfully subscribed to question.")
} else {
  button.attr("value", "Subscribe")
  window.alert("You have been successfully unsubscribed from question.")
}