config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  use_doorkeeper
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "questions#index"

  get :search, to: "search#index"

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit], shallow: true do
        resources :answers, except: %i[new edit]
      end
    end
  end

  resources :questions, shallow: true do
    post :subscribe, on: :member
    post :accept_vote, to: "votes#accept", on: :member, defaults: { votable: 'questions' }

    resources :comments, only: %i[create update destroy], defaults: { commentable: 'questions' }

    resources :answers, shallow: true, except: :index do
      post :accept_vote, to: "votes#accept", on: :member, defaults: { votable: 'answers' }
      resources :comments, only: %i[create update destroy], defaults: { commentable: 'answers' }
    
      post :mark_best, on: :member
    end
  end

  scope :active_storage, module: :active_storage, as: :active_storage do
      resources :attachments, only: :destroy
  end

  resources :awardings, only: :index

  mount ActionCable.server => '/cable'
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include Authorable

  default_scope { order(created_at: :asc) }

  belongs_to :commentable, polymorphic: true, touch: true

  validates :body, presence: true

  ThinkingSphinx::Callbacks.append(self, :behaviours => [:real_time])  
  after_create_commit :publish_comment

  private

  def publish_comment
    ActionCable.server.broadcast(
      "questions/#{question_id}/comments",
      to_json(include: :author)
    )
  end

  def question_id
    case commentable_type
    when 'Question'
      commentable_id
    when 'Answer'
      Answer.find(commentable_id).question_id
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_commentable, only: :create
  before_action :load_comment, only: %i[update destroy]

  authorize_resource

  respond_to :json

  def create
    @comment = @commentable.comments.new(comments_params.merge(author: current_user))
    
    respond_to do |format|
      if @comment.save
        format.json { render json: @comment, include: :author }
      else
        format.json { render json: @comment.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comments_params)
        format.json { render json: @comment }
      else
        format.json { render json: @comment.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    render json: { message: "Comment has been deleted." }
  end

  private

  def load_comment
    @comment = Comment.find(params[:id])
  end

  def load_commentable
    @commentable = commentable_name.classify.constantize.find(params["#{commentable_name.singularize}_id"])
  end

  def commentable_name
    params[:commentable]
  end

  def comments_params
    params.require(:comment).permit(:body)
  end
end

app/views/comments/_comment.html.slim
tr.comment *{ 'item-id' => comment.id }
  td
    - cache [comment, "body"] do
      span.comment_body   = comment.body
      span.comment_author = " - #{comment.author.email}"

    - if can? :update, comment
      = render "comments/form_inline", comment: comment
      td = link_to 'Edit', comment_path(comment), class: "form_inline_link"
    - if can? :destroy, comment  
      td = link_to 'Delete', comment_path(comment), data: {confirm: "Are you sure?", type: :json}, method: :delete, remote: true, class: "delete_comment"

app/views/comments/_form.html.slim
td.comment_form = form_with model: [commentable, commentable.comments.new], local: false, data: {type: :json} do |f|
  = f.text_area :body
  br
  = f.submit

app/views/comments/_form_inline.html.slim
= form_with model: comment,
            url: comment_path(comment), 
            local: false,
            method: :patch,
            class: "form_inline", 
            html: { data: { type: "json" }, style: 'display: none'} do |f|
  = f.text_area :body
  = f.submit