config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  use_doorkeeper
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "questions#index"

  get :search, to: "search#index"

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit], shallow: true do
        resources :answers, except: %i[new edit]
      end
    end
  end

  resources :questions, shallow: true do
    post :subscribe, on: :member
    post :accept_vote, to: "votes#accept", on: :member, defaults: { votable: 'questions' }

    resources :comments, only: %i[create update destroy], defaults: { commentable: 'questions' }

    resources :answers, shallow: true, except: :index do
      post :accept_vote, to: "votes#accept", on: :member, defaults: { votable: 'answers' }
      resources :comments, only: %i[create update destroy], defaults: { commentable: 'answers' }
    
      post :mark_best, on: :member
    end
  end

  scope :active_storage, module: :active_storage, as: :active_storage do
      resources :attachments, only: :destroy
  end

  resources :awardings, only: :index

  mount ActionCable.server => '/cable'
end

app/views/shared/_errors.html.slim
= content_tag :div, class: "errors"
  h2 = "Error".pluralize(resource.errors.count) + " ocurred:"
  ul
    - resource.errors.full_messages.each do |mes|
      li = mes

app/views/shared/_link_fields.html.slim
.nested-fields
  .field
    = f.label :title
    br
    = f.text_field :title
  .field
    = f.label :url
    br
    = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/shared/_nav.html.slim
ul.nav.justify-content-center
  - if current_user&.admin?
    li.nav-item = link_to "Sidekiq", sidekiq_web_path, class: "nav-link"
    li.nav-item = link_to "Oauth Apps", oauth_applications_path, class: "nav-link"
  li.nav-item = link_to "Search", search_path, class: "nav-link"
  li.nav-item = link_to "Questions", questions_path, class: "nav-link"
  li.nav-item = link_to "My awardings", awardings_path, class: "nav-link"
  - if current_user.present?
    li.nav-item = link_to "(#{current_user.email}) Sign out", destroy_user_session_path, method: :delete, id: "sign_out", class: "nav-link"
  - else
    li.nav-item = link_to "Sign in", new_user_session_path, method: :get, id: "sign_in", class: "nav-link"
    li.nav-item = link_to "Sign up", new_user_registration_path, method: :get, id: "sign_up", class: "nav-link"

app/views/shared/_votes.html.slim
table.vote
  tr
    td.up 
      = button_to send("accept_vote_#{resource.class.to_s.underscore}_path", resource), params: {preference: 1}, method: :post, remote: true, class: "accept_vote" do
        = octicon "chevron-up"
  tr
    td.rating = resource.rating
  tr 
    td.down 
      = button_to send("accept_vote_#{resource.class.to_s.underscore}_path", resource), params: {preference: -1}, method: :post, remote: true, class: "accept_vote" do
        = octicon "chevron-down"