config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  use_doorkeeper
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "questions#index"

  get :search, to: "search#index"

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit], shallow: true do
        resources :answers, except: %i[new edit]
      end
    end
  end

  resources :questions, shallow: true do
    post :subscribe, on: :member
    post :accept_vote, to: "votes#accept", on: :member, defaults: { votable: 'questions' }

    resources :comments, only: %i[create update destroy], defaults: { commentable: 'questions' }

    resources :answers, shallow: true, except: :index do
      post :accept_vote, to: "votes#accept", on: :member, defaults: { votable: 'answers' }
      resources :comments, only: %i[create update destroy], defaults: { commentable: 'answers' }
    
      post :mark_best, on: :member
    end
  end

  scope :active_storage, module: :active_storage, as: :active_storage do
      resources :attachments, only: :destroy
  end

  resources :awardings, only: :index

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Authorable
  include Commentable
  include Votable

  default_scope { order(best: :desc, created_at: :asc) }

  belongs_to :question, touch: true
  has_many :links, as: :linkable, dependent: :destroy
  has_many_attached :files

  validates :body, presence: true
  validates :body, uniqueness: { scope: :question_id, message: 'already exists for question.' }

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  ThinkingSphinx::Callbacks.append(self, :behaviours => [:real_time])  
  after_create_commit :publish_answer

  scope :recent_answers_for_follower, ->(follower) { where(question_id: Question.joins(:subscriptions, :answers).
                                                                        where("answers.created_at BETWEEN ? AND ? AND subscriptions.user_id = ?", 
                                                                        DailyDigest::TIME_RANGE.first, Time.now, follower.id)) }

  def mark_best!
    Answer.transaction do
      question.answers.update_all(best: false)
      update!(best: true)
      question.awarding&.update!(user: author)
    end
  end

  def publish_answer
    ActionCable.server.broadcast(
      "questions/#{question.id}/answers",
      to_json(include: [:author,
                        :question,
                        { files: { methods: %i[filename url] },
                          links: { methods: %i[gist? gist_id] } }],
              methods: :rating)
    )
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: %i[show]
  before_action :load_question, only: :create
  before_action :load_answer,   except: :create
  authorize_resource except: :mark_best

  respond_to :html, only: %i[edit update]
  respond_to :js, only: %i[create destroy mark_best]

  def show
    respond_with(@answer)
  end

  def edit
  end

  def update
    @answer.update(answer_params)
    respond_with @answer, location: -> { @answer.question }
  end

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(author_id: current_user.id)))
  end

  def destroy
    respond_with(@answer.destroy)
  end

  def mark_best
    authorize! :mark_best, @answer, :message => "Only author of the question can mark the best answer."
    @answer.mark_best!
  end

  private

  def answer_params
    params.require(:answer).permit(:question_id, :body, 
                                      files: [], links_attributes: [:id, :title, :url, :_destroy])
  end

  def load_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def load_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource only: %i[index show create]
  before_action :load_answer, only: %i[show update destroy]
  before_action :load_question, only: %i[index create]

  respond_to :json

  def index
    respond_with @question.answers, each_serializer: Api::V1::AnswersSerializer
  end

  def show
    respond_with @answer, serializer: Api::V1::AnswerSerializer
  end

  def create
    authorize! :create, Answer

    respond_with @answer = @question.answers.create(answer_params.merge(author_id: current_resource_owner.id)), serializer: Api::V1::AnswerSerializer
  end

  def update
    authorize! :update, @answer
    
    respond_to do |format|
      if @answer.update(answer_params)
        format.json { render json: @answer, serializer: Api::V1::AnswerSerializer }
      else
        format.json { render json: { "errors": @answer.errors }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :destroy, @answer
    
    respond_with(@answer.destroy)
  end

  private

  def answer_params
    params.require(:answer).permit(:question_id, :body, 
                                      links_attributes: [:id, :title, :url, :_destroy])
  end

  def load_question
    @question = Question.find(params[:question_id])
  end
  
  def load_answer
    @answer = Answer.find(params[:id])
  end
end

app/views/answers/_answer.html.slim
tr.answer class=(answer.best? ? "best" : nil) *{'item-id' => answer.id}
  td
    - cache [answer, "votes"] do
      = render partial: "shared/votes", locals: {resource: answer}

  td
    table
      tr 
        td 
          - if can? :mark_best, answer
            = button_to('Mark best', mark_best_answer_path(answer), remote: true, data: { type: :js }, class: (answer.best? ? "mark_best hide" : "mark_best"))
      
      - cache [answer, "body"] do
        tr 
          td
            strong Body: 
            = answer.body
        tr 
          td 
            strong Author: 
            = answer.author.email 
      
      - if answer.files.attached?
          tr
            td 
              strong Attachments: 
              br
              - answer.files.each do |file|
                = link_to file.filename.to_s, url_for(file)
                br

      - cache [answer, "links"] do
        - if answer.links.present?
          tr
            td
              table.links
                thead 
                  tr 
                    th = "Links:"
                - answer.links.each do |link|
                  tr 
                    td = link_to link.title, link.url, target: "_blank", data: (link.gist? ? {'gist-id' => link.gist_id} : '')

      tr
        td 
          - if can? :update, answer
            = button_to('Edit answer', edit_answer_path(answer), method: :get)
          - if can? :destroy, answer
            = button_to('Delete answer', answer_path(answer), method: :delete, remote: true, data: { confirm: "Are you sure?" }, class: "delete_answer")

      tr
        td
          table
            tr
              - cache [answer, "comments"] do
                td 
                  table.table.bordered.comments
                    - if answer.comments.present?
                      = render partial: 'comments/comment', collection: answer.comments
            tr
              - if current_user.present?
                - cache [answer, "new_comment_form"] do
                  = render partial: "comments/form", locals: {commentable: answer}
    

app/views/answers/_form.html.slim
br
  = form_with url: question_answers_path(question), model: question.answers.new, local: false, id: "direct_upload_form" do |f|
    h4 = f.label :body, "Your answer"
    br
    = f.text_area :body 
    br
    = f.file_field :files, multiple: true, direct_upload: true
    br
    h3 Links
    #links
      = f.fields_for :links do |link|
        = render 'shared/link_fields', f: link
      .links
        = link_to_add_association 'add link', f, :links,
          partial: 'shared/link_fields'
    br
    = f.submit

app/views/answers/create.js.erb
<% if @answer.persisted? %>
  $(".answers > tbody").append('<%= j render @answer %>');
<% end %>

$(".errors").empty();
<% if @answer.errors.present? %>
  $(".errors").append('<%= j render "shared/errors", resource: @answer %>');
<% else %>
  $("#direct_upload_form input[type=hidden][name='answer[files][]']").remove()
  $("#direct_upload_form")[0].reset()
<% end %>

app/views/answers/destroy.js.erb
$('.answers tr[item-id="<%= @answer.id %>"]').remove()

app/views/answers/edit.html.slim
h2 Edit answer
- if @answer.errors.present?
  = render "shared/errors", resource: @answer

= form_with model: @answer, local: true, id: "direct_upload_form" do |f|
  = f.label      :body
  br
  = f.text_area  :body
  br
  - if @answer.files.attached?
  table.attachments
    thead
      tr 
        th = "Attachments:"
    - @answer.files.each do |file|
      tr*{'attachment-id' => file.id}
        td = link_to file.filename.to_s, url_for(file)
        td = link_to "Delete", active_storage_attachment_path(file.id), method: :delete, remote: true, data: {confirm: "Are you sure?"}, class: "delete"
  = f.file_field :files, multiple: true, direct_upload: true
  h3 Links
  #links
    = f.fields_for :links do |link|
      = render 'shared/link_fields', f: link
    .links
      = link_to_add_association 'add link', f, :links,
        partial: 'shared/link_fields'
  br
  = f.submit
= link_to "Back to question", question_path(@answer.question)

app/views/answers/mark_best.js.erb
$(".answers > tbody > tr[item-id='<%= @answer.id %>']").prependTo(".answers > tbody");

$(".answers > tbody > tr").removeClass('best')
$(".answers > tbody > tr .mark_best").removeClass('hide')
$(".answers > tbody > tr[item-id='<%= @answer.id %>']").addClass('best')
$(".answers > tbody > tr[item-id='<%= @answer.id %>'] .mark_best").addClass('hide')